# example
example:
  hello: 'hello'
  hi:
    val: 'hi'
app:
  logger:
    # 项目日志存储路径，相对路径（相对本项目根目录）或绝对路径
    dir: './logs'
db:
  mysql:
    host: 'localhost'
    username: 'dbuser'
    password: 'dbpwd'
    database: 'nestdb'
    port: 3306
    charser: 'utf8mb4'
    logger: 'advanced-console'
    logging: false
    multipleStatements: true
    dropSchema: false
    # 生成环境false https://typeorm.io/data-source-options#common-data-source-options
    synchronize: false
    supportBigNumbers: true
    bigNumberStrings: true
  redis:
    host: 'localhost'
    port: 6379
    password: 12345678
    db: 0
ali:
  region: 'oss-cn-qingdao'
  # 阿里云账号AccessKey拥有所有API的访问权限，风险很高。强烈建议您创建并使用RAM用户进行API访问或日常运维，请登录RAM控制台创建RAM用户。
  accessKeyId: 'hjfdfjhgghjjk',
  accessKeySecret: 'yhghgfggdf',
  bucket: 'bjhkhjkxing'
xcx:
  # 小程序id
  AppID: 'wxdfakfjdkasju493fsd'
  # 秘钥
  AppSecret: 'kfdjaskfkasjflfji348590ufewj'
  jwt:
    secretkey: 'SKDFDUWKASFHSIUHWHEFJDIERFJSKDFJ'
    expiresin: '24h'